name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  publish_test:

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build distributions
        uses: ./.github/workflows/build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Tag a commit
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
