name: Publish to TestPyPI

on:
  workflow_dispatch:
    

jobs:
  publish_test:

    runs-on: "ubuntu-latest"

    permissions:
      id-token: write

    environment:
      name: testpypi
      url: https://test.pypi.org/project/mercapi/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build distributions
        uses: ./.github/workflows/build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/