name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  publish_test:

    runs-on: "ubuntu-latest"

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/mercapi/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build distributions
        uses: ./.github/workflows/build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Tag a commit
        run: |
          echo "TAG=v${{ inputs.version }}" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG
