name: Publish to TestPyPI

on:
  workflow_dispatch:
    

jobs:
  publish_test:

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build distributions
        uses: ./.github/workflows/build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
